# Generated by Django 2.2.6 on 2021-09-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210903_0932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='PostForm',
        ),
    ]
