# Generated by Django 2.2.6 on 2021-09-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210903_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostForm',
        ),
    ]
