# Generated by Django 2.2.16 on 2021-09-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210921_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
