# Generated by Django 2.2.16 on 2021-09-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
